stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/diamonds.csv
    - src/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    outs:
    - data/processed_data

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed_data
    - src/model_building.py

    params:
    - model_building.n_estimators
    - model_building.max_depth
    - model_building.learning_rate
    - model_building.random_state
    outs:
    - model/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json


metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
